export const PROTECTED_ROUTES = {
  DASHBOARD: "/dashboard",
  ARTICLES: "/articles",
  FLAGGED_ARTICLES: "/flagged-articles",
  PENDING_ARTICLES: "articles-pending",
  ARTICLE: "/articles/:id",
  REGISTER_TOPIC: "/register-topic",
  JST_PROJECTS: "/jst-projects",
  STATISTICS: "/statistics",
  MY_ENTRIES: "my-entries",
  FUNNY_MESSAGES: "funny-messages",
  CREATE_ARTICLE: "articles/new",
  FAVORITES_ARTICLES: "favorites-articles",
  MANAGE_USERS: "manage-users",
  MANAGE_PRODUCTS: "manage-products",
  NETWORK_TOOLS: "network-tools",
  ONBOARDING: "account-onboarding",
  USEFULLINKS: "useful-links",
  FAQ: "faq",
  CREATE_FAQ: "faq/create",
  MY_FLAGS: "my-flags",
  REPORTS: "reports",
  REPORTS_ID: "reports/:id",
  MY_WORKSPACES: "my-workspaces",
};
