import {
  AppWindow,
  ArrowDown,
  ArrowUp,
  BellElectric,
  Check,
  GraduationCap,
  LayoutPanelTop,
  LibraryBig,
  MonitorCheck,
  Plus,
  Presentation,
  School,
  Smartphone,
  TableOfContents,
  Tag,
  Trash2,
  TrendingUpDown,
} from "lucide-react";

export const ICONS: Record<string, React.ElementType> = {
  TableOfContents,
  Tag,
  GraduationCap,
  BellElectric,
  School,
  LibraryBig,
  LayoutPanelTop,
  Presentation,
  Smartphone,
  TrendingUpDown,
  MonitorCheck,
  AppWindow,
  ArrowDown,
  ArrowUp,
  Check,
  Plus,
  Trash2,
};

export const COLORS = [
  "blue",
  "green",
  "orange",
  "purple",
  "teal",
  "gray",
  "red",
  "yellow",
  "cyan",
  "pink",
  "amber",
];

export const COLOR_TOKEN_MAP: Record<string, string> = {
  blue: "#1E40AF",
  green: "#166534",
  orange: "#B45309",
  purple: "#6D28D9",
  teal: "#0F766E",
  gray: "#374151",
  red: "#B91C1C",
  yellow: "#B45309",
  cyan: "#0891B2",
  pink: "#BE185D",
  amber: "#D97706",
};
