import {
  Award,
  Brain,
  Castle,
  Cherry,
  Cog,
  Crown,
  Drum,
  Eye,
  Flower,
  Gem,
  Origami,
  Panda,
  PawPrint,
  PencilRuler,
  PenTool,
  PiggyBank,
  Pyramid,
  Rat,
  Rocket,
  Shield,
  Snowflake,
  Spade,
  Sprout,
  TowerControl,
  User,
  Zap,
} from "lucide-react";

export const iconOptions = [
  { name: "Crown", icon: Crown },
  { name: "Gem", icon: Gem },
  { name: "User", icon: User },
  { name: "Eye", icon: Eye },
  { name: "Zap", icon: Zap },
  { name: "Pyramid", icon: Pyramid },
  { name: "PencilRuler", icon: PencilRuler },
  { name: "PenTool", icon: PenTool },
  { name: "TowerControl", icon: TowerControl },
  { name: "Piggybank", icon: PiggyBank },
  { name: "Shield", icon: Shield },
  { name: "Snowflake", icon: Snowflake },
  { name: "Rat", icon: Rat },
  { name: "Sprout", icon: Sprout },
  { name: "Rocket", icon: Rocket },
  { name: "Castle", icon: Castle },
  { name: "Origami", icon: Origami },
  { name: "Panda", icon: Panda },
  { name: "Flower", icon: Flower },
  { name: "Drum", icon: Drum },
  { name: "Award", icon: Award },
  { name: "Cog", icon: Cog },
  { name: "Cherry", icon: Cherry },
  { name: "Brain", icon: Brain },
  { name: "Spade", icon: Spade },
  { name: "PawPrint", icon: PawPrint },
];

export const iconMap = Object.fromEntries(
  iconOptions.map(({ name, icon }) => [name, icon])
);
